# Generated by Django 5.2.6 on 2026-01-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
